version: '3.8'

name: hometopia

services:
  core-service:
    container_name: core-service
    image: core-service
    env_file:
      - .env
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8010:8010"
    networks:
      - hometopia-network

  gateway-service:
    container_name: gateway-service
    image: gateway-service
    env_file:
      - .env
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8000:8000"
    networks:
      - hometopia-network

  media-service:
    container_name: media-service
    image: media-service
    env_file:
      - .env
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8050:8050"
    networks:
      - hometopia-network

  rule-service:
    container_name: rule-service
    image: rule-service
    env_file:
      - .env
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8030:8030"
      - "8040:8040"
    networks:
      - hometopia-network

networks:
  hometopia-network:
    external: true