version: '3.8'

name: hometopia

services:
  core-service:
    container_name: core-service
    image: core-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_SCHEME: ${VAULT_SCHEME}
      VAULT_HOST: ${VAULT_SCHEME}
      VAULT_PORT: ${VAULT_PORT}
    ports:
      - "8010:8010"
    networks:
      - hometopia-network

  gateway-service:
    container_name: gateway-service
    image: gateway-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8000:8000"
    networks:
      - hometopia-network

  media-service:
    container_name: media-service
    image: media-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8050:8050"
    networks:
      - hometopia-network

  rule-service:
    container_name: rule-service
    image: rule-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8030:8030"
      - "8040:8040"
    networks:
      - hometopia-network

networks:
  hometopia-network:
    external: true