version: '3.8'

name: hometopia

services:
  hometopia-core-service:
    container_name: hometopia-core-service
    image: hometopia-core-service
    restart: unless-stopped
    build:
      context: ./core-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: core-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8010:8010"
    networks:
      - hometopia-network

  hometopia-gateway-service:
    container_name: hometopia-gateway-service
    image: hometopia-gateway-service
    restart: unless-stopped
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8000:8000"
    networks:
      - hometopia-network

  hometopia-media-service:
    container_name: hometopia-media-service
    image: hometopia-media-service
    restart: unless-stopped
    build:
      context: ./media-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: media-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8050:8050"
    networks:
      - hometopia-network

  hometopia-rule-service:
    container_name: hometopia-rule-service
    image: hometopia-rule-service
    restart: unless-stopped
    build:
      context: ./rule-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: rule-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8030:8030"
      - "8040:8040"
    networks:
      - hometopia-network

networks:
  hometopia-network:
    external: true