version: "3.8"

name: 'keycloak'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8008:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
#    volumes:
      - ./keycloak:/opt/keycloak/data/import
#    command: start-dev --import-realm
    command: start-dev
    networks:
      - hometopia-network

networks:
  hometopia-network:
    external: true