version: '3.8'

name: 'elk'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    restart: unless-stopped
    environment:
      node.name: es-node
      cluster.name: docker-cluster
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      xpack.license.self_generated.type: basic
      xpack.security.enabled: true
      ELASTIC_PASSWORD: hometopia
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      interval: 30s
      retries: 10
      test: [ "CMD-SHELL", "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null --user elastic:hometopia http://localhost:9200" ]
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.4
    restart: unless-stopped
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    command: >
      bash -c "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null --user elastic:genesis http://elasticsearch:9200/_security/user/kibana_system/_password -H 'Content-Type: application/json' -d '{\"password\": \"hometopia\"}' && /usr/local/bin/kibana-docker"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - hometopia-network

volumes:
  elasticsearch:
    driver: local

networks:
  hometopia-network:
    external: true