package com.hometopia.commons.enumeration;

public enum AssetCategory {
    TV,
    SOUND_SYSTEM,
    PROJECTOR,
    AIR_CONDITIONER,
    LIGHTING,
    AIR_PURIFIER,
    STOVE,
    MICROWAVE,
    OVEN,
    REFRIGERATOR,
    WATER_PURIFIER,
    RANGE_HOOD,
    BED,
    WARDROBE,
    FAN,
    NIGHT_LIGHT,
    SHOWER,
    BATHTUB,
    SINK,
    WATER_HEATER,
    EXHAUST_FAN,
    WASHING_MACHINE,
    DRYER,
    CLOTHES_RACK,
    IRON,
    LAPTOP,
    MOBILE_PHONE
}
